spring:
  datasource:
    url: jdbc:mysql://localhost/Grupo-14-bdd-OO2-2020?serverTimezone=UTC  # ?createDatabaseIfNotExist=true # esta linea ser√≠a para que se cree sola, pero no me anduvo
    username: root
    password: ser.23
    #initialization-mode: always #never
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
